name: Release

on:
  push:
    # If the commit is tagged with a version (e.g. "1.0.0") release the app after building
    tags: ["*"]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-11, windows-2022, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn
      - uses: battila7/get-version-action@v1.2.1
        id: get_version
      - name: Replace version
        run: yarn version --no-git-tag-version --new-version ${{ steps.get_version.outputs.version }}
      - name: Install rpmbuild
        run: sudo apt install -y rpm
        # Only install rpmbuild on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
      - name: Bundle & release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: "build"
          release: true
          github_token: ${{ secrets.GITHUB_PAT }}
          # macOS code signing certificate
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          # Windows code signing certificate
          windows_certs: ${{ secrets.windows_certs }}
          windows_certs_password: ${{ secrets.windows_certs_password }}
        env:
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
